# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='x_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='y_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
