# Generated by Django 1.10.1 on 2017-10-23 19:06

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venue", "0002_auto_20170710_1818"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="seat_map_dimensions",
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
