# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_venue_seat_map_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='map_address',
            field=models.TextField(blank=True),
        ),
    ]
