# Generated by Django 1.10.1 on 2017-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venue", "0004_venue_map_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="map_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
