version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - Dependencies
  ignore:
  - dependency-name: django
    versions:
    - ">= 2.a, < 3"
  - dependency-name: pytest-xdist
    versions:
    - "> 1.18.2"
  - dependency-name: django
    versions:
    - 3.1.7
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
