---
engines:
  prospector:
    enabled: false

  pylint:
    enabled: false
    python_version: 3
    exclude_paths:
      - tests/
      - karspexet/**/migrations/**/*
      - karspexet/**/test_*.py

  bandit:
    enabled: true
    exclude_paths:
      - tests/
      - karspexet/**/migrations/**/*
      - karspexet/**/test_*.py

  eslint:
    enabled: true
    exclude_paths:
      - assets/fonts/icomoon/**/*
