---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.py"
exclude_paths:
- tests/
- karspexet/**/migrations/**/*
- karspexet/**/test_*.py
