# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: assets/fonts/|assets/css/icons.css|static/fonts/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/rtts/djhtml
    rev: v1.5.0
    hooks:
      - id: djhtml
        args: [-t, "2"]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports"]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        args: [--fix]
        additional_dependencies:
          [
            "stylelint@13.2.1",
            "stylelint-config-idiomatic-order@8.1.0",
            "stylelint-config-prettier@9.0.3",
            "stylelint-config-standard@20.0.0",
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: assets/fonts/
        exclude_types: [html]
