# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='show.Production')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.Venue')),
            ],
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ('date',)},
        ),
    ]
