# Generated by Django 1.10.1 on 2017-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
