# Generated by Django 1.10.1 on 2017-11-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("show", "0002_show_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="production",
            name="alt_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
