# Generated by Django 1.10.1 on 2017-12-09 16:23

import django.utils.crypto
from django.db import migrations, models


def generate_show_slugs(apps, schema_editor):
    Show = apps.get_model('show', 'Show')
    for row in Show.objects.all():
        row.slug = row.id
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_production_alt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.CharField(null=True, max_length=20, unique=True),
        ),
        migrations.RunPython(generate_show_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="show",
            name="slug",
            field=models.CharField(
                default=lambda: django.utils.crypto.get_random_string(20),
                null=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
