# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_show_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
