# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_allow_blank_show_short_description_20180323_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='free_seating',
            field=models.BooleanField(default=False, help_text='Fri placering'),
        ),
    ]
