# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-09 12:04
from __future__ import unicode_literals

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
        ('venue', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
    ]
