# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_reservation_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
