# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 22:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
        ('ticket', '0007_timestamp_remaining_ticket_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', django.contrib.postgres.fields.hstore.HStoreField()),
                ('valid_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('seating_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.SeatingGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('normal', 'Fullpris'), ('student', 'Student')], default='normal', max_length=10),
        ),
    ]
