# Generated by Django 1.10.1 on 2017-05-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0008_add_pricing_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
