# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-11 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
        ('venue', '0002_auto_20170710_1818'),
        ('ticket', '0009_account_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set([('show', 'seat')]),
        ),
    ]
