# Generated by Django 1.10.1 on 2017-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_unique_ticket_per_seat_and_show_20170911_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
