# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import karspexet.ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='rebate_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='reservation',
        ),
        migrations.AddField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=karspexet.ticket.models._generate_random_code, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(default=karspexet.ticket.models._fifteenth_september_this_year),
        ),
    ]
