# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import karspexet.ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_reservation_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=karspexet.ticket.models._generate_voucher_code, max_length=16, unique=True),
        ),
    ]
