# Generated by Django 1.11.29 on 2020-07-11 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_ticket_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingmodel',
            name='seating_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.SeatingGroup'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.Account'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue.Seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='show.Show'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
