# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(verbose_name="date it's shown")),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('price', models.PositiveSmallIntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Show')),
            ],
        ),
    ]
